# Generated by Django 3.0.5 on 2020-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='bestplace',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bestplace',
            name='intro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bestplace',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bestplace',
            name='position',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='country',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trafood',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bestplace',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
