# Generated by Django 3.0.5 on 2020-05-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20200516_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafood',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
