# Generated by Django 3.0.5 on 2020-05-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_trafood_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestplace',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
