# Generated by Django 3.0.5 on 2020-05-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_bestplace_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestplace',
            name='intro',
        ),
    ]
