# Generated by Django 3.0.5 on 2020-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_remove_bestplace_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
