# Generated by Django 3.0.6 on 2020-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_language_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
