# Generated by Django 3.0.6 on 2020-05-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_auto_20200519_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='url',
            new_name='languageUrl',
        ),
    ]
