# Generated by Django 3.0.5 on 2020-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0009_auto_20200519_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='pron',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='country',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
