# Generated by Django 3.0.5 on 2020-05-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0011_auto_20200519_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='pronounce',
        ),
    ]
